/**
 * Friendly workspace-name generator.
 *
 * Produces names like "swift-piranha", "obsidian-meadow", "amber-orchid".
 * Inline word lists keep this dependency-free; the generator only needs to be
 * good enough that the user gets memorable distinct names instead of
 * "Untitled workspace" everywhere.
 */

const ADJECTIVES = [
  'amber',
  'azure',
  'brave',
  'bright',
  'calm',
  'clever',
  'cobalt',
  'crimson',
  'crisp',
  'dusty',
  'eager',
  'eerie',
  'electric',
  'emerald',
  'fierce',
  'fluent',
  'frosted',
  'gentle',
  'gilded',
  'graceful',
  'hidden',
  'humble',
  'icy',
  'indigo',
  'jolly',
  'keen',
  'lively',
  'lucid',
  'mellow',
  'misty',
  'modest',
  'nimble',
  'noble',
  'obsidian',
  'opaque',
  'patient',
  'peaceful',
  'plucky',
  'polite',
  'proud',
  'quiet',
  'radiant',
  'restless',
  'rugged',
  'silent',
  'silver',
  'snowy',
  'spry',
  'stellar',
  'stormy',
  'sturdy',
  'sunny',
  'swift',
  'tender',
  'twilight',
  'velvet',
  'vivid',
  'witty',
  'woolly',
  'zesty',
];

const NOUNS = [
  'aurora',
  'badger',
  'beacon',
  'birch',
  'breeze',
  'canyon',
  'cedar',
  'cinder',
  'cliff',
  'comet',
  'coral',
  'crater',
  'crescent',
  'dahlia',
  'delta',
  'dune',
  'ember',
  'falcon',
  'fern',
  'fjord',
  'forge',
  'galaxy',
  'gecko',
  'geyser',
  'glade',
  'glacier',
  'grove',
  'harbor',
  'heron',
  'iris',
  'island',
  'juniper',
  'kestrel',
  'lagoon',
  'lantern',
  'lily',
  'lotus',
  'meadow',
  'mesa',
  'monsoon',
  'moss',
  'oasis',
  'orchid',
  'otter',
  'panther',
  'piranha',
  'prairie',
  'quartz',
  'reef',
  'ridge',
  'river',
  'savanna',
  'sequoia',
  'spruce',
  'sunset',
  'tide',
  'tundra',
  'tulip',
  'valley',
  'willow',
];

function pick<T>(list: readonly T[]): T {
  const i = Math.floor(Math.random() * list.length);
  return list[i] as T;
}

/** Returns a friendly workspace name like "swift-piranha". */
export function generateWorkspaceName(): string {
  return `${pick(ADJECTIVES)}-${pick(NOUNS)}`;
}
